replicaCount: 1

strategy:
  type: Recreate

terminationGracePeriodSeconds: 30

image:
  repository: ghcr.io/gokabisa/wyze-bridge
  pullPolicy: IfNotPresent
  tag: ""

automountServiceAccountToken: false

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: wyze-bridge

credentialsSecret: wyze-bridge-credentials
webAuthSecret: wyze-bridge-webauth

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000
  extraPorts:
    - name: rtsp
      port: 8554
      targetPort: 8554
      protocol: TCP
    - name: hls
      port: 8888
      targetPort: 8888
      protocol: TCP
    - name: webrtc
      port: 8889
      targetPort: 8889
      protocol: TCP
    - name: webrtc-ice
      port: 8189
      targetPort: 8189
      protocol: UDP
    - name: rtmp
      port: 1935
      targetPort: 1935
      protocol: TCP

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 2
    memory: 2Gi

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podLabels: {}

securityContext:
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0

env:
  WB_AUTH: "True"
  FLASK_RUN_PORT: "5000"
  LLHLS: "false"
  REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
  SSL_CERT_FILE: "/etc/ssl/certs/ca-certificates.crt"

livenessProbe:
  tcpSocket:
    port: 5000
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5

readinessProbe:
  tcpSocket:
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 15
  failureThreshold: 10
